name: gs2m
channels:
  - nvidia/label/cuda-12.8.1
  - conda-forge
  - defaults
dependencies:
  - cuda-toolkit=12.8
  - matplotlib
  - numpy=1.26.4
  - python=3.10
  - pip=22.1
  - pytorch-gpu=2.9.1
  - pybind11
  - scikit-learn
  - scikit-image
  - setuptools=68
  - tensorboard
  - torchaudio=2.9.1
  - torchvision=0.24.1
  - pip:
    - submodules/pycolmap
    - submodules/gsplat
    - submodules/nvdiffrast
    - submodules/render-utils
    - submodules/fused-ssim
    - submodules/fused-bilagrid
    - submodules/nerfview
    - submodules/plas
    - cupy-cuda12x
    - einops
    - huggingface_hub
    - imageio[ffmpeg]
    - kornia
    - msgpack
    - numpy<2.0.0
    - nvidia-ncore
    - open3d==0.18.0
    - opencv-python
    - piexif
    - plyfile
    - splines
    - timm
    - torchmetrics[image]
    - torchpq
    - tqdm
    - trimesh
    - tyro>=0.8.8
    - viser
    - usd-core