name: gs2m
channels:
  - pytorch
  - nvidia/label/cuda-12.4.1
  - conda-forge
  - defaults
dependencies:
  - cuda-toolkit=12.4
  - einops
  - huggingface_hub
  - imageio
  - kornia
  - matplotlib
  - numpy=1.26.4
  - opencv
  - plyfile
  - python=3.10
  - pip=22.1
  - piexif
  - pytorch=2.4.1
  - pytorch-cuda=12.4
  - scikit-image
  - scikit-learn
  - setuptools=68
  - splines
  - tensorboard
  - timm
  - torchaudio=2.4.1
  - torchvision=0.19.1
  - torchmetrics
  - tqdm
  - trimesh
  - tyro>=0.8.8
  - viser
  - pip:
    - submodules/pycolmap
    - submodules/gsplat
    - submodules/nvdiffrast
    - submodules/render-utils
    - submodules/fused-ssim
    - submodules/fused-bilagrid
    - submodules/nerfview
    - submodules/ppisp
    - submodules/plas
    - cupy-cuda12x
    - msgpack
    - open3d==0.18.0
    - nvidia-ncore
    - torchpq
    - usd-core